-- Setup storage bucket for generated packages
-- This bucket will store rule packages generated by the wizard

-- Create the storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'generated-packages',
  'generated-packages',
  true, -- Public bucket for easy access
  52428800, -- 50MB limit per file
  ARRAY[
    'application/zip',
    'application/x-sh',
    'application/json',
    'text/plain',
    'application/octet-stream'
  ]
) ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Set up storage policies for the bucket
-- Allow public read access (anyone can download packages)
CREATE POLICY "Public read access for generated packages" ON storage.objects
FOR SELECT USING (bucket_id = 'generated-packages');

-- Allow authenticated and anonymous users to upload packages
CREATE POLICY "Anyone can upload generated packages" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'generated-packages');

-- Allow cleanup operations
CREATE POLICY "Allow package cleanup" ON storage.objects
FOR DELETE USING (bucket_id = 'generated-packages'); 